services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    networks:
      - proxy-network
    restart: always

networks:
  proxy-network:
    external: true
