---
- name: Copy caddy to the server
  ansible.builtin.copy:
    src: "./files/caddy"
    dest: "/root/app"
    mode: "0644"

- name: Copy uptime-kuma the server
  ansible.builtin.copy:
    src: "./files/uptime-kuma"
    dest: "/root/app"
    mode: "0644"

- name: Create docker network
  ansible.builtin.command: >
    docker network create proxy-network
  failed_when: false
  become: true

- name: Run docker-compose up for Caddy
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /root/app/caddy
  become: true

- name: Run docker-compose up for Uptime Kuma
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /root/app/uptime-kuma
  become: true
