services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy-network:
    external: true
