---
- name: Ensure gvisor is downloaded
  ansible.builtin.get_url:
    url: "{{ gvisor_src_base_url }}/runsc"
    dest: /usr/local/bin/runsc
    checksum: "sha512:{{ gvisor_src_base_url }}/runsc.sha512"
    mode: "0744"

- name: Ensure containerd-shim is downloaded
  ansible.builtin.get_url:
    url: "{{ gvisor_src_base_url }}/containerd-shim-runsc-v1"
    dest: /usr/local/bin/containerd-shim-runsc-v1
    checksum: "sha512:{{ gvisor_src_base_url }}/containerd-shim-runsc-v1.sha512"
    mode: "0744"

- name: Ensure /etc/docker exists
  ansible.builtin.file:
    dest: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure gvisor is installed
  ansible.builtin.copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: "Restart Docker service"
