---
- name: Ensure Docker and related packages are installed
  ansible.builtin.package:
    name:
      - docker
      - docker-cli-compose
      - linux-virt
      - linux-virt-dev
    state: latest
    update_cache: true
